### ISSUE TITLE
JdbcProfile TypeInfo for slick-joda-mapper integration

### ISSUE THREAD

**Issue by rowlandwatkins** [nafg/slick-additions#8]
Hi,

I'm trying to use slick-joda-mapper with slick-additions, however, I'm hitting the following hurdle:

JdbcProfile has no TypeInfo for type com.github.tototoshi.slick.JodaDateTimeMapper$TypeMappers$/TIMESTAMP

My driver extends the scala.slick.driver.H2Driver with KeyedTableComponent

Since KeyTableComponent extends JdbcProfile this might be causing some hassle, but I'm not sure.

Any hints on how to use Joda datatypes?

Cheers,

Rowland

**Comment by nafg** [comment]
@rowlandwatkins can you please respond, if this is solved please close the issue.
